<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryAndRegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        DB::insert("INSERT INTO `countries` (`continent_code`, `code`, `alpha2`, `alpha3`, `name_en`, `name_fr`) VALUES
            ('AS', 4, 'AF', 'AFG', 'Afghanistan', 'Afghanistan'),
            ('EU', 8, 'AL', 'ALB', 'Albania', 'Albanie'),
            ('AN', 10, 'AQ', 'ATA', 'Antarctica', 'Antarctique'),
            ('AF', 12, 'DZ', 'DZA', 'Algeria', 'Algérie'),
            ('OC', 16, 'AS', 'ASM', 'American Samoa', 'Samoa Américaines'),
            ('EU', 20, 'AD', 'AND', 'Andorra', 'Andorre'),
            ('AF', 24, 'AO', 'AGO', 'Angola', 'Angola'),
            ('NA', 28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda'),
            ('EU', 31, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaïdjan'),
            ('SA', 32, 'AR', 'ARG', 'Argentina', 'Argentine'),
            ('OC', 36, 'AU', 'AUS', 'Australia', 'Australie'),
            ('EU', 40, 'AT', 'AUT', 'Austria', 'Autriche'),
            ('NA', 44, 'BS', 'BHS', 'Bahamas', 'Bahamas'),
            ('AS', 48, 'BH', 'BHR', 'Bahrain', 'Bahreïn'),
            ('AS', 50, 'BD', 'BGD', 'Bangladesh', 'Bangladesh'),
            ('EU', 51, 'AM', 'ARM', 'Armenia', 'Arménie'),
            ('NA', 52, 'BB', 'BRB', 'Barbados', 'Barbade'),
            ('EU', 56, 'BE', 'BEL', 'Belgium', 'Belgique'),
            ('NA', 60, 'BM', 'BMU', 'Bermuda', 'Bermudes'),
            ('AS', 64, 'BT', 'BTN', 'Bhutan', 'Bhoutan'),
            ('SA', 68, 'BO', 'BOL', 'Bolivia', 'Bolivie'),
            ('EU', 70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'),
            ('AF', 72, 'BW', 'BWA', 'Botswana', 'Botswana'),
            ('AN', 74, 'BV', 'BVT', 'Bouvet Island', 'Île Bouvet'),
            ('SA', 76, 'BR', 'BRA', 'Brazil', 'Brésil'),
            ('NA', 84, 'BZ', 'BLZ', 'Belize', 'Belize'),
            ('AS', 86, 'IO', 'IOT', 'British Indian Ocean Territory', 'Territoire Britannique de l''Océan Indien'),
            ('OC', 90, 'SB', 'SLB', 'Solomon Islands', 'Îles Salomon'),
            ('NA', 92, 'VG', 'VGB', 'British Virgin Islands', 'Îles Vierges Britanniques'),
            ('AS', 96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunéi Darussalam'),
            ('EU', 100, 'BG', 'BGR', 'Bulgaria', 'Bulgarie'),
            ('AS', 104, 'MM', 'MMR', 'Myanmar', 'Myanmar'),
            ('AF', 108, 'BI', 'BDI', 'Burundi', 'Burundi'),
            ('EU', 112, 'BY', 'BLR', 'Belarus', 'Bélarus'),
            ('AS', 116, 'KH', 'KHM', 'Cambodia', 'Cambodge'),
            ('AF', 120, 'CM', 'CMR', 'Cameroon', 'Cameroun'),
            ('NA', 124, 'CA', 'CAN', 'Canada', 'Canada'),
            ('AF', 132, 'CV', 'CPV', 'Cape Verde', 'Cap-vert'),
            ('NA', 136, 'KY', 'CYM', 'Cayman Islands', 'Îles Caïmanes'),
            ('AF', 140, 'CF', 'CAF', 'Central African', 'République Centrafricaine'),
            ('AS', 144, 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka'),
            ('AF', 148, 'TD', 'TCD', 'Chad', 'Tchad'),
            ('SA', 152, 'CL', 'CHL', 'Chile', 'Chili'),
            ('AS', 156, 'CN', 'CHN', 'China', 'Chine'),
            ('AS', 158, 'TW', 'TWN', 'Taiwan', 'Taïwan'),
            ('AS', 162, 'CX', 'CXR', 'Christmas Island', 'Île Christmas'),
            ('AS', 166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)'),
            ('SA', 170, 'CO', 'COL', 'Colombia', 'Colombie'),
            ('AF', 174, 'KM', 'COM', 'Comoros', 'Comores'),
            ('AF', 175, 'YT', 'MYT', 'Mayotte', 'Mayotte'),
            ('AF', 178, 'CG', 'COG', 'Republic of the Congo', 'République du Congo'),
            ('AF', 180, 'CD', 'COD', 'The Democratic Republic Of The Congo', 'République Démocratique du Congo'),
            ('OC', 184, 'CK', 'COK', 'Cook Islands', 'Îles Cook'),
            ('NA', 188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica'),
            ('EU', 191, 'HR', 'HRV', 'Croatia', 'Croatie'),
            ('NA', 192, 'CU', 'CUB', 'Cuba', 'Cuba'),
            ('EU', 196, 'CY', 'CYP', 'Cyprus', 'Chypre'),
            ('EU', 203, 'CZ', 'CZE', 'Czech Republic', 'République Tchèque'),
            ('AF', 204, 'BJ', 'BEN', 'Benin', 'Bénin'),
            ('EU', 208, 'DK', 'DNK', 'Denmark', 'Danemark'),
            ('NA', 212, 'DM', 'DMA', 'Dominica', 'Dominique'),
            ('NA', 214, 'DO', 'DOM', 'Dominican Republic', 'République Dominicaine'),
            ('SA', 218, 'EC', 'ECU', 'Ecuador', 'Équateur'),
            ('NA', 222, 'SV', 'SLV', 'El Salvador', 'El Salvador'),
            ('AF', 226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinée Équatoriale'),
            ('AF', 231, 'ET', 'ETH', 'Ethiopia', 'Éthiopie'),
            ('AF', 232, 'ER', 'ERI', 'Eritrea', 'Érythrée'),
            ('EU', 233, 'EE', 'EST', 'Estonia', 'Estonie'),
            ('EU', 234, 'FO', 'FRO', 'Faroe Islands', 'Îles Féroé'),
            ('SA', 238, 'FK', 'FLK', 'Falkland Islands', 'Îles (malvinas) Falkland'),
            ('AN', 239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud'),
            ('OC', 242, 'FJ', 'FJI', 'Fiji', 'Fidji'),
            ('EU', 246, 'FI', 'FIN', 'Finland', 'Finlande'),
            ('EU', 248, 'AX', 'ALA', 'Åland Islands', 'Îles Åland'),
            ('EU', 250, 'FR', 'FRA', 'France', 'France'),
            ('SA', 254, 'GF', 'GUF', 'French Guiana', 'Guyane Française'),
            ('OC', 258, 'PF', 'PYF', 'French Polynesia', 'Polynésie Française'),
            ('AN', 260, 'TF', 'ATF', 'French Southern Territories', 'Terres Australes Françaises'),
            ('AF', 262, 'DJ', 'DJI', 'Djibouti', 'Djibouti'),
            ('AF', 266, 'GA', 'GAB', 'Gabon', 'Gabon'),
            ('EU', 268, 'GE', 'GEO', 'Georgia', 'Géorgie'),
            ('AF', 270, 'GM', 'GMB', 'Gambia', 'Gambie'),
            ('AS', 275, 'PS', 'PSE', 'Occupied Palestinian Territory', 'Territoire Palestinien Occupé'),
            ('EU', 276, 'DE', 'DEU', 'Germany', 'Allemagne'),
            ('AF', 288, 'GH', 'GHA', 'Ghana', 'Ghana'),
            ('EU', 292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar'),
            ('OC', 296, 'KI', 'KIR', 'Kiribati', 'Kiribati'),
            ('EU', 300, 'GR', 'GRC', 'Greece', 'Grèce'),
            ('NA', 304, 'GL', 'GRL', 'Greenland', 'Groenland'),
            ('NA', 308, 'GD', 'GRD', 'Grenada', 'Grenade'),
            ('NA', 312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe'),
            ('OC', 316, 'GU', 'GUM', 'Guam', 'Guam'),
            ('NA', 320, 'GT', 'GTM', 'Guatemala', 'Guatemala'),
            ('AF', 324, 'GN', 'GIN', 'Guinea', 'Guinée'),
            ('SA', 328, 'GY', 'GUY', 'Guyana', 'Guyana'),
            ('NA', 332, 'HT', 'HTI', 'Haiti', 'Haïti'),
            ('AN', 334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Îles Heard et Mcdonald'),
            ('EU', 336, 'VA', 'VAT', 'Vatican City State', 'Saint-Siège (état de la Cité du Vatican)'),
            ('NA', 340, 'HN', 'HND', 'Honduras', 'Honduras'),
            ('AS', 344, 'HK', 'HKG', 'Hong Kong', 'Hong-Kong'),
            ('EU', 348, 'HU', 'HUN', 'Hungary', 'Hongrie'),
            ('EU', 352, 'IS', 'ISL', 'Iceland', 'Islande'),
            ('AS', 356, 'IN', 'IND', 'India', 'Inde'),
            ('AS', 360, 'ID', 'IDN', 'Indonesia', 'Indonésie'),
            ('AS', 364, 'IR', 'IRN', 'Islamic Republic of Iran', 'République Islamique d''Iran'),
            ('AS', 368, 'IQ', 'IRQ', 'Iraq', 'Iraq'),
            ('EU', 372, 'IE', 'IRL', 'Ireland', 'Irlande'),
            ('AS', 376, 'IL', 'ISR', 'Israel', 'Israël'),
            ('EU', 380, 'IT', 'ITA', 'Italy', 'Italie'),
            ('AF', 384, 'CI', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire'),
            ('NA', 388, 'JM', 'JAM', 'Jamaica', 'Jamaïque'),
            ('AS', 392, 'JP', 'JPN', 'Japan', 'Japon'),
            ('AS', 398, 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan'),
            ('AS', 400, 'JO', 'JOR', 'Jordan', 'Jordanie'),
            ('AF', 404, 'KE', 'KEN', 'Kenya', 'Kenya'),
            ('AS', 408, 'KP', 'PRK', 'Democratic People''s Republic of Korea', 'République Populaire Démocratique de Corée'),
            ('AS', 410, 'KR', 'KOR', 'Republic of Korea', 'République de Corée'),
            ('AS', 414, 'KW', 'KWT', 'Kuwait', 'Koweït'),
            ('AS', 417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirghizistan'),
            ('AS', 418, 'LA', 'LAO', 'Lao People''s Democratic Republic', 'République Démocratique Populaire Lao'),
            ('AS', 422, 'LB', 'LBN', 'Lebanon', 'Liban'),
            ('AF', 426, 'LS', 'LSO', 'Lesotho', 'Lesotho'),
            ('EU', 428, 'LV', 'LVA', 'Latvia', 'Lettonie'),
            ('AF', 430, 'LR', 'LBR', 'Liberia', 'Libéria'),
            ('AF', 434, 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Jamahiriya Arabe Libyenne'),
            ('EU', 438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein'),
            ('EU', 440, 'LT', 'LTU', 'Lithuania', 'Lituanie'),
            ('EU', 442, 'LU', 'LUX', 'Luxembourg', 'Luxembourg'),
            ('AS', 446, 'MO', 'MAC', 'Macao', 'Macao'),
            ('AF', 450, 'MG', 'MDG', 'Madagascar', 'Madagascar'),
            ('AF', 454, 'MW', 'MWI', 'Malawi', 'Malawi'),
            ('AS', 458, 'MY', 'MYS', 'Malaysia', 'Malaisie'),
            ('AS', 462, 'MV', 'MDV', 'Maldives', 'Maldives'),
            ('AF', 466, 'ML', 'MLI', 'Mali', 'Mali'),
            ('EU', 470, 'MT', 'MLT', 'Malta', 'Malte'),
            ('NA', 474, 'MQ', 'MTQ', 'Martinique', 'Martinique'),
            ('AF', 478, 'MR', 'MRT', 'Mauritania', 'Mauritanie'),
            ('AF', 480, 'MU', 'MUS', 'Mauritius', 'Maurice'),
            ('NA', 484, 'MX', 'MEX', 'Mexico', 'Mexique'),
            ('EU', 492, 'MC', 'MCO', 'Monaco', 'Monaco'),
            ('AS', 496, 'MN', 'MNG', 'Mongolia', 'Mongolie'),
            ('EU', 498, 'MD', 'MDA', 'Republic of Moldova', 'République de Moldova'),
            ('EU', 499, 'ME', 'MNE', 'Montenegro', 'Monténégro'),
            ('AS', 500, 'MS', 'MSR', 'Montserrat', 'Montserrat'),
            ('AF', 504, 'MA', 'MAR', 'Morocco', 'Maroc'),
            ('AF', 508, 'MZ', 'MOZ', 'Mozambique', 'Mozambique'),
            ('AS', 512, 'OM', 'OMN', 'Oman', 'Oman'),
            ('AF', 516, 'NA', 'NAM', 'Namibia', 'Namibie'),
            ('OC', 520, 'NR', 'NRU', 'Nauru', 'Nauru'),
            ('AS', 524, 'NP', 'NPL', 'Nepal', 'Népal'),
            ('EU', 528, 'NL', 'NLD', 'Netherlands', 'Pays-Bas'),
            ('NA', 530, 'AN', 'ANT', 'Netherlands Antilles', 'Antilles Néerlandaises'),
            ('NA', 531, 'CW', 'CUW', 'CuraÃ§ao', 'CuraÃ§ao'),
            ('NA', 533, 'AW', 'ABW', 'Aruba', 'Aruba'),
            ('NA', 534, 'SX', 'SXM', 'Sint Maarten (Netherlands)', 'Sint Maarten (Néerlandaises)'),
            ('NA', 535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'),
            ('OC', 540, 'NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie'),
            ('OC', 548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu'),
            ('OC', 554, 'NZ', 'NZL', 'New Zealand', 'Nouvelle-Zélande'),
            ('NA', 558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua'),
            ('AF', 562, 'NE', 'NER', 'Niger', 'Niger'),
            ('AF', 566, 'NG', 'NGA', 'Nigeria', 'Nigéria'),
            ('OC', 570, 'NU', 'NIU', 'Niue', 'Niué'),
            ('OC', 574, 'NF', 'NFK', 'Norfolk Island', 'Île Norfolk'),
            ('EU', 578, 'NO', 'NOR', 'Norway', 'Norvège'),
            ('OC', 580, 'MP', 'MNP', 'Northern Mariana Islands', 'Îles Mariannes du Nord'),
            ('OC', 581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'Îles Mineures Éloignées des États-Unis'),
            ('OC', 583, 'FM', 'FSM', 'Federated States of Micronesia', 'États Fédérés de Micronésie'),
            ('OC', 584, 'MH', 'MHL', 'Marshall Islands', 'Îles Marshall'),
            ('OC', 585, 'PW', 'PLW', 'Palau', 'Palaos'),
            ('AS', 586, 'PK', 'PAK', 'Pakistan', 'Pakistan'),
            ('NA', 591, 'PA', 'PAN', 'Panama', 'Panama'),
            ('OC', 598, 'PG', 'PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'),
            ('SA', 600, 'PY', 'PRY', 'Paraguay', 'Paraguay'),
            ('SA', 604, 'PE', 'PER', 'Peru', 'Pérou'),
            ('AS', 608, 'PH', 'PHL', 'Philippines', 'Philippines'),
            ('OC', 612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn'),
            ('EU', 616, 'PL', 'POL', 'Poland', 'Pologne'),
            ('EU', 620, 'PT', 'PRT', 'Portugal', 'Portugal'),
            ('AF', 624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau'),
            ('AS', 626, 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste'),
            ('NA', 630, 'PR', 'PRI', 'Puerto Rico', 'Porto Rico'),
            ('AS', 634, 'QA', 'QAT', 'Qatar', 'Qatar'),
            ('AF', 638, 'RE', 'REU', 'Réunion', 'Réunion'),
            ('EU', 642, 'RO', 'ROU', 'Romania', 'Roumanie'),
            ('EU', 643, 'RU', 'RUS', 'Russian Federation', 'Fédération de Russie'),
            ('AF', 646, 'RW', 'RWA', 'Rwanda', 'Rwanda'),
            ('NA', 652, 'BL', 'BLM', 'Saint Barthelemy', 'Sainte-Barthélémie'),
            ('AF', 654, 'SH', 'SHN', 'Saint Helena', 'Sainte-Hélène'),
            ('NA', 659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'),
            ('NA', 660, 'AI', 'AIA', 'Anguilla', 'Anguilla'),
            ('NA', 662, 'LC', 'LCA', 'Saint Lucia', 'Sainte-Lucie'),
            ('NA', 663, 'MF', 'MAF', 'Saint Martin', 'Sainte-Martin'),
            ('NA', 666, 'PM', 'SPM', 'Saint-Pierre and Miquelon', 'Saint-Pierre-et-Miquelon'),
            ('NA', 670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les Grenadines'),
            ('EU', 674, 'SM', 'SMR', 'San Marino', 'Saint-Marin'),
            ('AF', 678, 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe'),
            ('AS', 682, 'SA', 'SAU', 'Saudi Arabia', 'Arabie Saoudite'),
            ('AF', 686, 'SN', 'SEN', 'Senegal', 'Sénégal'),
            ('EU', 688, 'RS', 'SRB', 'Serbia', 'Serbie'),
            ('AF', 690, 'SC', 'SYC', 'Seychelles', 'Seychelles'),
            ('AF', 694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone'),
            ('AS', 702, 'SG', 'SGP', 'Singapore', 'Singapour'),
            ('EU', 703, 'SK', 'SVK', 'Slovakia', 'Slovaquie'),
            ('AS', 704, 'VN', 'VNM', 'Vietnam', 'Viet Nam'),
            ('EU', 705, 'SI', 'SVN', 'Slovenia', 'Slovénie'),
            ('AF', 706, 'SO', 'SOM', 'Somalia', 'Somalie'),
            ('AF', 710, 'ZA', 'ZAF', 'South Africa', 'Afrique du Sud'),
            ('AF', 716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe'),
            ('EU', 724, 'ES', 'ESP', 'Spain', 'Espagne'),
            ('AF', 732, 'EH', 'ESH', 'Western Sahara', 'Sahara Occidental'),
            ('AF', 728, 'SS', 'SSD', 'South Sudan', 'Soudan du Sud'),
            ('AF', 736, 'SD', 'SDN', 'Sudan', 'Soudan'),
            ('SA', 740, 'SR', 'SUR', 'Suriname', 'Suriname'),
            ('EU', 744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard etÎle Jan Mayen'),
            ('AF', 748, 'SZ', 'SWZ', 'Swaziland', 'Swaziland'),
            ('EU', 752, 'SE', 'SWE', 'Sweden', 'Suède'),
            ('EU', 756, 'CH', 'CHE', 'Switzerland', 'Suisse'),
            ('AS', 760, 'SY', 'SYR', 'Syrian Arab Republic', 'République Arabe Syrienne'),
            ('AS', 762, 'TJ', 'TJK', 'Tajikistan', 'Tadjikistan'),
            ('AS', 764, 'TH', 'THA', 'Thailand', 'Thaïlande'),
            ('AF', 768, 'TG', 'TGO', 'Togo', 'Togo'),
            ('OC', 772, 'TK', 'TKL', 'Tokelau', 'Tokelau'),
            ('OC', 776, 'TO', 'TON', 'Tonga', 'Tonga'),
            ('NA', 780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago'),
            ('AS', 784, 'AE', 'ARE', 'United Arab Emirates', 'Émirats Arabes Unis'),
            ('AF', 788, 'TN', 'TUN', 'Tunisia', 'Tunisie'),
            ('EU', 792, 'TR', 'TUR', 'Turkey', 'Turquie'),
            ('AS', 795, 'TM', 'TKM', 'Turkmenistan', 'Turkménistan'),
            ('NA', 796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Îles Turks et Caïques'),
            ('OC', 798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu'),
            ('AF', 800, 'UG', 'UGA', 'Uganda', 'Ouganda'),
            ('EU', 804, 'UA', 'UKR', 'Ukraine', 'Ukraine'),
            ('EU', 807, 'MK', 'MKD', 'The Former Yugoslav Republic of Macedonia', 'L''ex-République Yougoslave de Macédoine'),
            ('AF', 818, 'EG', 'EGY', 'Egypt', 'Égypte'),
            ('EU', 826, 'GB', 'GBR', 'United Kingdom', 'Royaume-Uni'),
            ('EU', 831, 'GG', 'GGY', 'Guernsey, Bailiwick of', 'Guernsey, Bailiwick of'),
            ('EU', 832, 'JE', 'JEY', 'Jersey, Bailiwick of', 'Jersey, Bailiwick of'),
            ('EU', 833, 'IM', 'IMN', 'Isle of Man', 'Île de Man'),
            ('AF', 834, 'TZ', 'TZA', 'United Republic Of Tanzania', 'République-Unie de Tanzanie'),
            ('NA', 840, 'US', 'USA', 'United States', 'États-Unis'),
            ('NA', 850, 'VI', 'VIR', 'U.S. Virgin Islands', 'Îles Vierges des États-Unis'),
            ('AF', 854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso'),
            ('SA', 858, 'UY', 'URY', 'Uruguay', 'Uruguay'),
            ('AS', 860, 'UZ', 'UZB', 'Uzbekistan', 'Ouzbékistan'),
            ('SA', 862, 'VE', 'VEN', 'Venezuela', 'Venezuela'),
            ('OC', 876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis et Futuna'),
            ('OC', 882, 'WS', 'WSM', 'Samoa', 'Samoa'),
            ('AS', 887, 'YE', 'YEM', 'Yemen', 'Yémen'),
            ('AF', 894, 'ZM', 'ZMB', 'Zambia', 'Zambie');
        ");

        $data = [
            'CM' => [
                'Extrême-Nord',
                'Nord',
                'Adamaoua',
                'Est',
                'Centre',
                'Sud',
                'Littoral',
                'Ouest',
                'Nord-Ouest',
            ],
            'BJ' => [
                'Alibori',
                'Atacora',
                'Atlantique',
                'Borgou',
                'Collines',
                'Couffo',
                'Donga',
                'Littoral',
                'Mono',
                'Ouémé',
                'Plateau',
                'Zou'
            ],
            'GA' => [
                'Estuaire',
                'Haut-Ogooué',
                'Moyen-Ogooué',
                'Ngounié',
                'Nyanga',
                'Ogooué-Ivindo',
                'Ogooué-Lolo',
                'Ogooué-Maritime',
                'Woleu-Ntem',
            ],
            'CI' => [
                'Abidjan',
                'Yamoussoukro',
                'N’Zi',
                'Iffou',
                'Bélier',
                'Moronou',
                'Indénié-Djuablin',
                'Sud-Comoé',
                'Folon',
                'Kabadougou',
                'Gôh',
                'Lôh-Djiboua',
                'Agnéby-Tiassa',
                'Mé',
                'Grands-Ponts',
                'Tonkpi',
                'Cavally',
                'Guémon',
                'Haut-Sassandra',
                'Marahoué',
                'Poro',
                'Tchologo',
                'Bagoué',
                'Nawa',
                'San-Pédro',
                'Gbôklé',
                'Hambol',
                'Gbêkê',
                'Béré',
                'Bafing',
                'Worodougou',
                'Bounkani',
                'Gontougo',
            ],
            'GQ' => [
                'Annobón',
                'Bioko-Norte',
                'Bioko-Sur',
                'Centro-Sur',
                'Kié-Ntem',
                'Litoral',
                'Wele-Nzas',
                'Djibloho',
            ],
            'CG' => [
                'Likouala',
                'Sangha',
                'Cuvette Ouest',
                'Cuvette',
                'Plateaux',
                'Pool',
                'Bouenza',
                'Lékoumou',
                'Niari',
                'Kouilou',
                'Pointe-Noire',
                'Brazzaville',
            ],
            'CD' => [
                'Bas-Uele',
                'Équateur',
                'Haut-Katanga',
                'Haut-Lomami',
                'Haut-Uele',
                'Ituri',
                'Kasaï',
                'Kasaï-Oriental',
                'Kasaï-Occidental',
                'Kinshasa',
                'Kongo-Central',
                'Kwango',
                'Kwilu',
                'Lomami',
                'Lualaba',
                'Mai-Ndombe',
                'Maniema',
                'Mongala',
                'Nord-Kivu',
                'Nord-Ubangi',
                'Sankuru',
                'Sud-Kivu',
                'Sud-Ubangi',
                'Tanganyika',
                'Tshopo',
                'Tshuapa',
            ],
            'TD' => [
                'Centre',
                'Centre-Est',
                'Centre-Ouest',
                'Est',
                'Extrême-Nord',
                'Sud-Est',
                'N’Djamena',
                'Nord',
                'Nord-Est',
                'Ouest',
                'Sud',
                'Sud-Ouest',
            ],
            'CF' => [
                'Bamingui-Bangoran',
                'Basse-Kotto',
                'Haute-Kotto',
                'Haut-Mbomou',
                'Kémo',
                'Lobaye',
                'Mambéré-Kadéï',
                'Mbomou',
                'Nana-Mambéré',
                "Ombella-M'Poko",
                'Ouaka',
                'Ouham',
                'Ouham-Pendé',
                'Vakaga',
                'Gribingui économique',
                'Sangha économique',
            ],
            'BF' => [
                'Boucle du Mouhoun',
                'Cascades',
                'Centre',
                'Centre-Est',
                'Centre-Nord',
                'Centre-Ouest',
                'Centre-Sud',
                'Est',
                'Hauts-Bassins',
                'Nord',
                'Plateau-Central',
                'Sahel',
                'Sud-Ouest',
            ],
            'GN' => [
                'Boké',
                'Conakry',
                'Farana',
                'Kankan',
                'Kindia',
                'Labé',
                'Mamou',
                "N'Zérékoré",
            ],
            'ML' => [
                'Kayes',
                'Koulikoro',
                'Bamako',
                'Sikasso',
                'Ségou',
                'Mopti',
                'Tombouctou',
                'Gao',
                'Kidal',
                'Taoudénit',
                'Ménaka',
            ],
            'MR' => [
                'Adrar',
                'Assaba',
                'Brakna',
                'Dakhlet Nouadhibou',
                'Gorgol',
                'Guidimakha',
                'Hodh Ech Chargui',
                'Hodh El Gharbi',
                'Inchiri',
                'Nouakchott-Nord',
                'Nouakchott-Ouest',
                'Nouakchott-Sud',
                'Tagant',
                'Tiris Zemmour',
                'Trarza',
            ],
            'NE' => [
                'Agadez',
                'Diffa',
                'Dosso',
                'Maradi',
                'Niamey',
                'Tahoua',
                'Tillabéri',
                'Zinder',
            ],
            'SN' => [
                'Dakar',
                'Ziguinchor',
                'Diourbel',
                'Saint-Louis',
                'Tambacounda',
                'Kaolack',
                'Thiès',
                'Louga',
                'Fatick',
                'Kolda',
                'Matam',
                'Kaffrine',
                'Kédougou',
                'Sédhiou',
            ],
            'TG' => [
                'Région maritime',
                'Région des plateaux,',
                'Région centrale',
                'région de la Kara',
                'Région des savanes',
            ],
        ];

        foreach ($data as $key => $regions) {
            $country = Country::firstWhere([
                'alpha2' => $key
            ]);
            $country->status = true;
            $country->save();

            foreach ($regions as $value) {
                $region = Region::firstOrCreate([
                    'country_id' => $country->id,
                    'name' => $value
                ]);
            }
        }
    }
}
